# -*- coding: utf-8 -*-
"""build_config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x_J5DoS7NTKWgpY_c_eRsRAP8VqIZ1sd
"""

# Library
import os
from datetime import datetime
import configparser
import getpass

# configParser
config = configparser.ConfigParser()

# DB INFO
config['dbinfo'] = {}
print("DB 정보를 입력해주세요.")

# INPUT
host = input("Host: ")
config['dbinfo']['host'] = host

dbname = input("DB name: ")
config['dbinfo']['dbname'] = dbname

port = input("Port: ")
config['dbinfo']['port'] = port

user = input("Username: ")
config['dbinfo']['user'] = user

password = getpass.getpass("Password: ")
config['dbinfo']['password'] = password

# DIRECTORY INFO
config['directory'] = {}
print("디렉토리 정보를 입력해주세요.")

# INPUT
dqd_dir = input("DQD directory: ")
if dqd_dir == "":
    dqd_dir = os.getcwd()
    print(dqd_dir)
config['directory']['dqd_dir'] = dqd_dir

output_folder = input("outputFolder: ")
if output_folder == "":
    output_folder = 'result_'+str(datetime.now().date()).replace('-','_')
    print(output_folder)
config['directory']['outputFolder'] = output_folder

#  save file
with open(os.path.join(os.getcwd(),'config.ini'), 'w', encoding = 'utf-8') as configfile:
  config.write(configfile)

os.system("pause")